GET http://localhost:8000/api/categories

###
GET http://localhost:8000/api/categories/ba09c121-394c-4a60-a04d-46af2297cd87

###
POST http://localhost:8000/api/categories
Content-Type: application/json

{
    "name": "Movie"
}

###
PUT http://localhost:8000/api/categories/b4452093-964b-4ab8-9876-74da32ced784
Content-Type: application/json

{
    "name": "Movie"
}

###
DELETE  http://localhost:8000/api/categories/d6471e3e-cb0f-486d-bfba-cf77d8182e30
Content-Type: application/json