version: '3'

services:

    backend:
        build: ./backend
        entrypoint: ./.docker/entrypoint.sh
        volumes:
            - ./backend:/var/www
            - ./backend/.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        ports:
          - 8000:8000
